### PR TITLE
Expose page information in writer in order to handle metadata, try 2.

### PR DESCRIPTION
**Pull request by kalaspuffar**
We had a requirement from MTM to add metadata of the highest page number within a PEF file. 

This is the second try to get the information required to fetch the last page number. Again, maybe the simples solution is the best one. This small change makes volumes available for use, changing the method to the public. I've made the volume get function something cached for future calls, so we don't get different results from the first and second run.

I'll get the volumes first to prepare the metadata and then run the writer function to write out the final volumes.

My code to extract the last page number is

```
            List<Volume> vList = (List<Volume>) ((FormatterImpl)formatter).getVolumes();
            int numVolumes = vList.size();
            for (Volume v : vList) {
                for (Section s : v.getSections()) {
                    List<Page> pList = (List<Page>) s.getPages();
                    if (s.getSectionProperties().duplex()) {
                        numSheets += Math.ceil((double) pList.size() / 2d);
                    } else {
                        numSheets += pList.size();
                    }
                    for (Page p : pList) {
                        for (Row r : p.getRows()) {
                            numChars += r.getChars().length();
                        }
                        if (lastPage < ((PageImpl)p).getPageNumber()) {
                            lastPage = ((PageImpl)p).getPageNumber();
                        }
                    }
                }
            }
```

The final output in the PEF would be something like

```
<ext:sheets>34</ext:sheets>
<ext:pages>56</ext:pages>
<ext:volumes>1</ext:volumes>
<ext:kiloChars>21</ext:kiloChars>
```

This was earlier done via an XSLT after the PEF was created, but the page's meta tag (highest page number in the file) was a bit kludgy to do after the PEF was generated; I don't think there is a good way to get that information in XSLT.

What do you think about this solution @bertfrees?

Best regards
Daniel

### CODE REVIEW

**Review by bertfrees — CHANGES_REQUESTED** [review]
I was thinking some solution to pass on metadata, but not the data itself.

Your solution adds a new way to get the data in addition to the existing `write(PagedMediaWriter)`. I'm not sure that is such a great idea because:
- It's not good if an API has multiple ways to do the same thing.
- You will still cast the `Page` objects to `PageImpl` in order to get the page number information, so it's not that much of an improvement compared to your [initial code to extract the last page number](https://github.com/mtmse/dotify.library/pull/44#issue-1255821329). I'd like to avoid having to do it like that in DAISY Pipeline if possible.

You'll say: then why don't we remove `write(PagedMediaWriter)` and add `getPageNumber` to `Page`? But I don't think that's the direction we should be going. I would try to stay faithful to the API that we currently have (`PagedMediaWriter`) and improve it with metadata arguments/methods.

I'm OK with the PR if you revert the last two commits. The first commit is quite harmless. Ideally I think we should find a way to get the page number info without having to do hacks, but it's not so important for me at this moment.

**Comment by bertfrees** [comment]
> Currently reviewing the other PR for hyphenation but it will take time and I want to do a release after that so we can update the baseline and be able to find issues in the future.

OK. So you want to update the baseline and not use the `allowsEndingVolumeOnHyphen` and `allowsEndingPageOnHyphen` settings to get the same results? Both ways are fine for me. Just checking.

**Comment by kalaspuffar** [comment]
PR approved, running regression tests.

**Comment by kalaspuffar** [comment]
Regression tests passed, merging.

**Pull request merged**
